Hide labels for blobs
git-visual/git-visual pull request #180
Opened 2022-02-23 15:31 UTC by joglr

Fixes #179
Fixes #196
Fixes #197

2022-02-24 09:02 UTC, tjomson requested changes
Clicking a node causes this error
![billede](https://user-images.githubusercontent.com/23435481/155492483-8c30f948-1e2d-44db-96db-e21a82565174.png)

2022-02-25 10:55 UTC, emiljapelt commented
Filter function

.filter((d) => d.data.type === "tree" || (d.data as HydratedGitBlobObject).noLines >= 40)

2022-02-25 16:04 UTC, hojelse commented
Legend component doesn't show up

![legend_is_gone](https://user-images.githubusercontent.com/34659757/155747587-8ef6225b-f698-4800-8e42-b569c63260b9.png)

2022-02-25 16:07 UTC, hojelse requested changes
Legend component doesn't show up

![legend_is_gone](https://user-images.githubusercontent.com/34659757/155748080-c890746d-af63-4f81-9107-02619c813770.png)

2022-02-25 16:17 UTC, joglr commented on app/src/components/Tooltip.tsx
> +  pointer-events: none;
This still overflows the body

2022-02-28 09:55 UTC, hojelse approved these changes

2022-02-28 09:56 UTC, tjomson approved these changes
🚀

2022-02-28 09:57 UTC, merged