Add search functionality
git-visual/git-visual pull request #184
Opened 2022-02-23 21:02 UTC by tjomson

resolves #182

2022-02-24 11:43 UTC, joglr requested changes

2022-02-24 11:43 UTC, joglr commented on app/src/components/SearchBar.css
> +input:focus {
Hiding the outline of a focused search field is not good for accessibility
https://www.a11yproject.com/posts/never-remove-css-outlines/

2022-02-24 11:43 UTC, joglr commented on app/src/components/SearchBar.css
> +input {
Could we use styled-components to keep the styling solution consistent? See examples in util.tsx

2022-02-24 11:44 UTC, joglr commented
Great addition! Will test it in a bit.

2022-02-24 11:45 UTC, joglr commented on app/src/components/BubbleChart.css
> +  /* stroke-width: 0; */
Commented out code

2022-02-28 14:39 UTC, joglr approved these changes

2022-02-28 15:00 UTC, hojelse requested changes
![search_state](https://user-images.githubusercontent.com/34659757/156005343-2aa656f6-6d8f-442e-933f-1ad3ac9ac321.png)

"Searching..." status is active just after reload

2022-02-28 15:17 UTC, hojelse approved these changes

2022-02-28 15:17 UTC, merged