Refactor to render SVG element with React
git-visual/git-visual pull request #226
Opened 2022-03-02 12:01 UTC by joglr

Resolves #214 
Resolves #212 
Resolves #183

2022-03-02 14:48 UTC, joglr commented on app/package.json
> +    "clsx": "^1.1.1",
This dependency is unused

2022-03-02 14:49 UTC, joglr commented on app/src/components/Chart.css
>  .search-match-title {
This declaration is unused

2022-03-02 14:49 UTC, joglr commented on app/src/components/Chart.css
> +.name-text {
This declaration is unused

2022-03-02 14:50 UTC, joglr commented on app/src/components/SearchBar.tsx
> +    1,
Revert this

2022-03-02 14:50 UTC, joglr commented on app/src/components/SidePanel.tsx
> +`
This introduces an issue when the sidebar is overflowing, a horizontal scrollbar is shown

2022-03-02 14:51 UTC, joglr commented on app/src/util.ts
> +export function diagonal(d: HierarchyRectangularNode<unknown>) {
This is unused

2022-03-04 09:19 UTC, tjomson reviewed
Search animations are different between bubble and tree map, is this intended?

When changing from tree to bubble map, there is a short delay before the folder names are shown.

Search field seems inconsistent. Sometimes very quick and smooth, other times laggy

2022-03-04 14:05 UTC, hojelse requested changes
Can we improve this?

1x click of a node or 1x character typed in search triggers 278 calls to unionAuthors()
![280](https://user-images.githubusercontent.com/34659757/156777465-dba67481-312a-42b3-8709-a514c1a8295e.png)

- Providers() - 1x
  - getDefaultStore() - 1x
    - setupMetricsCache() foreach "blob" (72 blobs) - 72x
      - setDominanceColor() - 72x
      - setDominantAuthorColor() - 72x

both setDominanceColor and SetDominantAuthorColor calls unionAuthors() 

1 reload triggers 2x getDefaultStore() - 2 * (72 + 72) ≃ 278

1 click is sometimes a double click, triggering 4x getDefaultStore() - 4 * (72 + 72) = 576

2022-03-07 14:01 UTC, tjomson commented
> Can we improve this?
> 
> ![588](https://user-images.githubusercontent.com/34659757/156798726-eee22e0f-c87c-4f1c-9f36-1d3c430cf145.png)
> 
> 1 click of a svg node triggers:
> 
>     * Providers() - 1x
>       
>       * getDefaultStore() - 1x
>         
>         * setupMetricsCache() foreach "blob" (72 blobs) - 72x
>           
>           * setDominanceColor() - 72x
>             
>             * unionAuthors() - 72x
>           * setDominantAuthorColor() - 72x
>             
>             * unionAuthors() - 72x
> 
> 
> both setDominanceColor and SetDominantAuthorColor calls unionAuthors()
> 
> 1 browser reload triggers 2x Providers() calls - 2 * (72 + 72) ≃ 278
> 
> 1 click is sometimes a double click, triggering 4x Providers() calls - 4 * (72 + 72) = 576

2022-03-07 14:20 UTC, joglr commented
> Search animations are different between bubble and tree map, is this intended?

I have made this more consistent.

> When changing from tree to bubble map, there is a short delay before the folder names are shown.

Issue was created for looking into this issue.

> Search field seems inconsistent. Sometimes very quick and smooth, other times laggy

I have readded the debounce.

2022-03-07 14:51 UTC, tjomson approved these changes
🚀🥌

2022-03-07 14:52 UTC, merged